### ISSUE TITLE
Support downloading of all tracks

### ISSUE THREAD

**Issue by isaachinman** [rwieruch/favesound-mobx#3]
I would be interested in contributing to this project if download of any/all tracks is a feature in the pipeline. 

Clearly streaming a SoundCloud track is essentially downloading an 128kbps mp3 file, I would like the ability to save this file for offline use.

Not sure how the owner of this repo feels about this kind of usage (might be against SoundCloud TOC). Let me know.

**Comment by rwieruch** [comment]
I am so sorry that I never came back to this issue! 

In general it would be a cool feature, but I am unsure about the TOC by SoundCloud. Someone would need to investigate. Otherwise I would be very open for the feature. The [favesound-redux](https://github.com/rwieruch/favesound-redux) could have it as well.

**Comment by isaachinman** [comment]
@rwieruch No worries, I no longer use this application, but definitely would change my SoundCloud use entirely to any client which allows downloads easily/quickly. I suspect this is completely against TOC.
