### ISSUE TITLE
Enhancement: Migrate React.PropTypes to use prop-types package for React 15.4

### ISSUE THREAD

**Issue by rwieruch** [rwieruch/favesound-mobx#6]
The newest version of React extracts PropTypes to its own library. It would be cool to use the new library. In a sibling project the refactoring was already done: https://github.com/rwieruch/favesound-redux/pull/42

**Comment by field0917** [comment]
@rwieruch Hi, I have already created a pull request for this issue, however there is a new problem: 

<img width="1004" alt="screen shot 2017-06-16 at 3 59 53 pm copy" src="https://user-images.githubusercontent.com/19654067/27247416-074c574e-52ad-11e7-85c0-1d499dcf800a.png">

According to the documentation of prop-types: 
<img width="931" alt="screen shot 2017-06-16 at 4 01 38 pm" src="https://user-images.githubusercontent.com/19654067/27247439-341fbc8e-52ad-11e7-9427-f9f5a5603844.png">
It seems like one of the package is using the old syntax but I am not sure which one. Could you give me some hint please?

**Comment by rwieruch** [comment]
Hi @field0917 Thanks for your PR! I would assume, since it uses the same libraries than https://github.com/rwieruch/favesound-redux except for mobx and [mobx-react](https://github.com/mobxjs/mobx-react) that the warning could come from one of these libraries? In another PR it could be worth a shot to upgrade the mobx-react library, even though I am unsure about the recent breaking changes that will come with the upgrade.

Nevertheless, I assume that I can merge the PR, because only the Warning shows up? The mobx-react library upgrade could be another PR. Thanks for your help! 👍

**Comment by rwieruch** [comment]
@field0917 I upgraded the library versions, but I am still seeing the Warning :( https://github.com/rwieruch/favesound-mobx/commit/b79f54802108d297c5206274bd1f65d9a8ef2db2

**Comment by field0917** [comment]
I'll try to fix this warning later today.

**Comment by rwieruch** [comment]
Yes, give it a shot @field0917 Nevertheless, the PR got merged 👍 Thank you very much!

**Comment by field0917** [comment]
@rwieruch 

![](https://user-images.githubusercontent.com/19654067/27247416-074c574e-52ad-11e7-85c0-1d499dcf800a.png)

The above issue was caused by the inconsistency of React(15.0.x) and prop-types(15.5), I'll create a PR to upgrade React version to 15.6.x. 

After upgrading react, these warnings will come up:
<img width="1264" alt="screen shot 2017-06-18 at 11 54 05 pm" src="https://user-images.githubusercontent.com/19654067/27272963-c18675c4-5481-11e7-87f4-7477cea066ac.png">
I think it could be caused by react-router@3.0.0, since we have already migrated our source code to prop-types, I'll try to migrate react-router to the latest version and see how it goes.
